# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-17 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('authors', models.CharField(blank=True, max_length=1000, null=True)),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=200, null=True)),
                ('keywords', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('public_or_not', models.IntegerField(blank=True, null=True)),
                ('abstract', models.CharField(blank=True, max_length=10000, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('file_location', models.CharField(blank=True, max_length=1000, null=True)),
                ('uploader_id', models.IntegerField()),
                ('upload_date', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('publication_id', models.IntegerField()),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('credit_point', models.FloatField(default=1000)),
                ('group_id', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('assessor_notes', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
